### ISSUE TITLE
sometimes got an error 'No transport could be initialized successfully...'

### ISSUE THREAD

**Issue by jibenziliao** [olofd/react-native-signalr#13]
It connected failed sometimes,but it worked sometimes.
And I got this error:
"Error: No transport could be initialized successfully. Try specifying a different transport or none at all for auto initialization."

This is my code:
connection.start({transport: 'webSockets'}).done(() => {
  console.log('success');
}).fail(() => {
  console.log('error')
});
connection.error(function(error){
  console.log(error)//this prints that error.
});

**Comment by vahidhiv** [comment]
I use the sample code and watching console. It can't connect through websocket and trying to downgrade and finally it is connecting through long polling. What 's wrong?
Is it related to server's signalr version or something?

**Comment by olofd** [comment]
@vahidhiv Very hard to tell what's wrong from these vauge descriptions.

**Comment by vahidhiv** [comment]
@olofd I can send whatever is needed!
Log of console is enough?

**Comment by olofd** [comment]
Start with that. post I here.

**Comment by olofd** [comment]
@vahidhiv @jibenziliao I've just released 0.0.11. It contains a fix for suppressed error messages. It also contains a new README.md with new test code that runs agains a test-server I've setup in Azure. @jibenziliao Please see if you can reproduce your error against the test-server and also post the logs you already have!

**Comment by jibenziliao** [comment]
It always works fine with test test-server.
<img width="1251" alt="success" src="https://cloud.githubusercontent.com/assets/12134347/21974182/23c3c228-dc00-11e6-80ed-b236041c3638.png">
I think there is something wrong with my server or the network.
<img width="1273" alt="bug" src="https://cloud.githubusercontent.com/assets/12134347/21974191/2e131be8-dc00-11e6-9650-724207fd6d66.png">
If I use the original webSocket,it got the response code of 503 sometimes with my server.
<img width="1248" alt="bug2" src="https://cloud.githubusercontent.com/assets/12134347/21974193/33ec118c-dc00-11e6-98dd-289c25a9fa10.png">
My partner will fix the bug with the server.
Thank you very much!

**Comment by olofd** [comment]
Ah. Glad that the test server came to use. Good luck finding your bug!
