### ISSUE TITLE
Server side OnConnected() not triggered

### ISSUE THREAD

**Issue by kevinNgws** [olofd/react-native-signalr#15]
Server side OnConnected() is not been called whenever the client establishes a connection. 
`public override Task OnConnected()
        {
            return base.OnConnected();
        }
`
The same goes to OnDisconnected(). 

Even though the server method is not been called, there is still a connection between the client and server, and a connection id is generated. 

Please advice. 
I'm using the following libs:
react-native-signalr: 0.0.10
react-native: 0.39.0

**Comment by olofd** [comment]
Post some sample js-code here please. (I have used OnConnected with this library before and it should work). 

And please update to `react-native-signalr : 1.0.0`

**Comment by kevinNgws** [comment]
The code as below:
`connection = signalr.hubConnection(socketUrl);
    connection.logging = true;

    proxy = connection.createHubProxy(Constant.PROXY_HUB);

    return (dispatch) => {
        connection.start().done(() => {
            Reactotron.log('Now connected, connection ID=' + connection.id);

            dispatch({
                type: ActionTypes.ESTABLISH_CONNECTION_SUCCESS,
                payload: {
                    Activity: ActionTypes.ESTABLISH_CONNECTION_SUCCESS,
                    ConnectionId: connection.id
                }
            });

            // Connection-handling
            connection.connectionSlow(function () {
                Reactotron.log('Connection slow');
                dispatch({
                    type: ActionTypes.CONNECTION_SLOW,
                    payload: {
                        Activity: ActionTypes.CONNECTION_SLOW
                    }
                });
            });

            connection.reconnecting(function () {
                Reactotron.log('Connection reconnecting');
            });

            connection.reconnected(function () {
                Reactotron.log('Connection reconnected');
            });

            connection.disconnected(function () {
                Reactotron.log('Connection disconnected');
            });

            connection.error(function (error) {
                Reactotron.log('Connection error');
                dispatch({
                    type: ActionTypes.CONNECTION_HAS_ERROR,
                    payload: {
                        Activity: ActionTypes.CONNECTION_HAS_ERROR,
                        Error: error
                    }
                });
            });


        }).fail((error) => {
            Reactotron.log('Connection failed');
            Reactotron.log(error);
            dispatch({
                type: ActionTypes.ESTABLISH_CONNECTION_FAIL,
                payload: {
                    Activity: ActionTypes.ESTABLISH_CONNECTION_FAIL,
                }
            });
        });

        dispatch({
            type: ActionTypes.ESTABLISH_CONNECTION_REQUEST,
            payload: {
                Activity: ActionTypes.ESTABLISH_CONNECTION_REQUEST
            }
        });
    };`

I gotten the connection id so I doubt there is problem with the code.
Let me try updating the version to 1.0.0 and get back to you.

Thanks for the fast response!

**Comment by kevinNgws** [comment]
Hi, 
There is still issue with the server method not being called, even though i had upgraded to 1.0.0

**Comment by olofd** [comment]
It works here if I add a listener to the hub.
Tested on example project and it works.
I think you need to do this in signalr.

~~~~~~~
proxy = connection.createHubProxy(Constant.PROXY_HUB);

proxy.on('someMethodOnTheHub', (argOne) => {
    //I think you have to listen to a hub-method for lifecycle-events to fire on that hub.
    //Please read signalr-docs.
});

return (dispatch) => {
    connection.start().done(() => {
        Reactotron.log('Now connected, connection ID=' + connection.id);

        dispatch({
            type: ActionTypes.ESTABLISH_CONNECTION_SUCCESS,
            payload: {
                Activity: ActionTypes.ESTABLISH_CONNECTION_SUCCESS,
                ConnectionId: connection.id
            }
        });

        // Connection-handling
        connection.connectionSlow(function () {
            Reactotron.log('Connection slow');
            dispatch({
                type: ActionTypes.CONNECTION_SLOW,
                payload: {
                    Activity: ActionTypes.CONNECTION_SLOW
                }
            });
        });

        connection.reconnecting(function () {
            Reactotron.log('Connection reconnecting');
        });

        connection.reconnected(function () {
            Reactotron.log('Connection reconnected');
        });

        connection.disconnected(function () {
            Reactotron.log('Connection disconnected');
        });

        connection.error(function (error) {
            Reactotron.log('Connection error');
            dispatch({
                type: ActionTypes.CONNECTION_HAS_ERROR,
                payload: {
                    Activity: ActionTypes.CONNECTION_HAS_ERROR,
                    Error: error
                }
            });
        });


    }).fail((error) => {
        Reactotron.log('Connection failed');
        Reactotron.log(error);
        dispatch({
            type: ActionTypes.ESTABLISH_CONNECTION_FAIL,
            payload: {
                Activity: ActionTypes.ESTABLISH_CONNECTION_FAIL,
            }
        });
    });

    dispatch({
        type: ActionTypes.ESTABLISH_CONNECTION_REQUEST,
        payload: {
            Activity: ActionTypes.ESTABLISH_CONNECTION_REQUEST
        }
    });
};
~~~~~~~

**Comment by olofd** [comment]
My explanation for this: SignalR is a bit strange here. But you established a successful connection to the server by calling connection.start().
But you did not connect to your Hub. You only do this if you set up listener for that hub before calling connection.start. And lifecycle-events are only handled on the hub itself.

**Comment by kevinNgws** [comment]
Yes, it works! 

> But you did not connect to your Hub. You only do this if you set up listener for that hub before calling connection.start. And lifecycle-events are only handled on the hub itself.

Strange indeed! 
Nonetheless, thank you so much for the support!
