### ISSUE TITLE
This browser doesn't support SSE.

### ISSUE THREAD

**Issue by WellMafra** [olofd/react-native-signalr#19]
I'm working with Android simulator, and I'm receiving the error:

![error signalr](https://cloud.githubusercontent.com/assets/7647730/23526939/b1c1ecea-ff72-11e6-8d7a-fd9afb3a3fe7.PNG)

Additional Info:
Windows 10 64bits
Android: Nexus_5X_API_25_x86 - Android 6.0
Node: 3.10.10
React-native:  0.41.2
React: 15.4.2
react-native-signalr: 1.0.0

**Comment by olofd** [comment]
hmm.. I have no idea why that is.. webSockets should not fail on android. But I have no test environment here, so I have to send you hunting by yourself for that bug. look at the closed issues, have had some connection issues before, and you might find something there.

Can maybe help you out in a couple of days if you have not solved it by then. really busy here right now with other projects.

**Comment by jp928** [comment]
Make sure you opened websocket on server side. Test is quite simple. Make a test.html and add all the javavascript dependencies.

**Comment by WellMafra** [comment]
On my webproject, I'm always receiving the error: 

![erro websocket2](https://cloud.githubusercontent.com/assets/7647730/23551476/869ec366-fff5-11e6-888e-915124d5b7c7.PNG)

But, it connects normally. I do not know if there is something wrong on my IIS or web.config

**Comment by olofd** [comment]
Any progress here?

**Comment by sophanox** [comment]
Hey olofd, 

Sorry to hijack this thread but I've had a nightmare getting websockets to connect and I have finally just solved it. They would very occasionally connect in my case, with no apparent reasoning behind it. 

What I found was that if I disabled remote debugging it worked completely fine. I'm thinking the debugging must add some sort of overhead which cause the websocket connection to not be made in time, and thus fail.

I've also found that if I add the necessary access control headers to my web.config file:
```  <system.webServer>
      <customHeaders>
        <add name="Access-Control-Allow-Origin" value="http://localhost:8081" />
        <add name="Access-Control-Allow-Headers" value="Content-Type" />
        <add name="Access-Control-Allow-Methods" value="GET, POST, PUT, DELETE, OPTIONS" />
        <add name="Access-Control-Allow-Credentials" value="true" />
      </customHeaders>
  </system.webServer>
```
This allows serverSentEvents to work, which thus allow the connection and upgrade it to websockets - so you can still use the debugger.

Hope this helps someone!

Cheers

**Comment by olofd** [comment]
@sophanox Interesting. If you have the time, please add this to the README.md, or write up something I can paste there and I'll commit it straight up.

**Comment by olofd** [comment]
@WellMafra Any progress on your side?

**Comment by olofd** [comment]
Closing after no replay from @WellMafra
