### ISSUE TITLE
Question: Using Query String

### ISSUE THREAD

**Issue by oatcrunch** [olofd/react-native-signalr#22]
Hi,

Just a simple query, how do I include query string using this library? The example in C# would be as follows:

var qs = "username=rendang";
            var url = "http://192.168.93.139/SignalRHub/";
            hubConnection = new HubConnection(url, qs);

Do we have the equivalent way of doing this? I tried using the traditional way using this library, but doesn't seem to work ie:

let qs = "username=rendang";
        let url = "http://192.168.93.139/SignalRHub";
        let fullUrl = url + "?" + qs;
const connection = signalr.hubConnection(fullUrl);

And this way as well:

let qs = "username=rendang";
        let url = "http://192.168.93.139/SignalRHub";

        let fullUrl = url;
        const connection = signalr.hubConnection(fullUrl, qs);

Appreciate some advice.

Note: Sorry, I am very new to JS and ES6 language.

**Comment by oatcrunch** [comment]
Hi, is there any kind soul with the knowledge to help on the above query? If the this feature exists kindly provide some guidance on how can it be done; or any workaround will also be fine.

Thanks in advance.

**Comment by olofd** [comment]
I think you do it this way, by sending it in the options-object.
~~~js
const connection = signalr.hubConnection(fullUrlWithoutQueryString, {
 qs : "username=rendang"
});
~~~

Let me know if it does not work!

**Comment by oatcrunch** [comment]
Hi @olofd . I have tested your suggested method. It works :) Thanks for your help.

**Comment by olofd** [comment]
@oatcrunch Great! Then I'm closing this issue.
