### ISSUE TITLE
what is best way for catching server errors without red screen of death

### ISSUE THREAD

**Issue by osmanov** [olofd/react-native-signalr#25]
Awesome module,thank you very much for your work!
I have a question-what is the best way for catching  server errors without red screen of death?
         
```js
connection.start().done(()=>{
  connection.error( error => {
      //here i get the error from the server
    /*console.log(error.message)-->`it has exceeded the inactivity timeout of 50000 ms. Stopping the connection.` 
    but I can't handle this error here, because the red screen from simulator shoots immediately-`cannot read property supportsKeepAlive of null`*/
  });
})

```
Thank you!

**Comment by epodgaetskiy** [comment]
I have same problem.

**Comment by brunobraun** [comment]
Same problem. I created a handler for the AppState change so when the app state = "background" I stop the connection.. something like this:

```
_handleAppStateChange = (nextAppState) => {
     if(nextAppState === 'background') {
      this.connectionSignalR.stop();
    }
  }
```

and I restarted the connection in the "disconnected" signalr event... 

for my needs, it worked, hope it can help you

**Comment by osmanov** [comment]
Thanks @brunobraun, it helped me.

**Comment by dengue8830** [comment]
In my case, stopping it in the background gave me a problem, when I started signalr it was stays stuck in connecting state, and only connected when i came back to the app. So i stopped and restarted signalr on 'active'  AppState

**Comment by manjeets12** [comment]
@brunobraun sample code please, I mean more than that _handleAppStateChange change function.Will be great help 
Thanks
