### ISSUE TITLE
"Error during negotiation request. " error will shown up if the server is down.

### ISSUE THREAD

**Issue by lesliesam** [olofd/react-native-signalr#3]
Should that exception be caught by the connection.error() function instead of thrown to user?

**Comment by olofd** [comment]
Yes. Will fix this weekend.

**Comment by olofd** [comment]
@lesliesam I have moved away from es6-promises now, and use https://github.com/zzdhidden/node-jquery-deferred this instead for better compatibility with signalr. Pleas check out v0.0.7 and see if it works for you!
