### ISSUE TITLE
connection failure issue

### ISSUE THREAD

**Issue by sammosampson** [olofd/react-native-signalr#4]
When there is no internet connection and a connection.start() is attempted .fail() fires as expected, but the error is propogated out after exiting the fail() closure and we end up with the familiar RN red screen. Any ideas?

**Comment by olofd** [comment]
Will take a look tomorrow.

**Comment by sammosampson** [comment]
Any joy on this?

**Comment by sammosampson** [comment]
Just upgraded from 0.04 to 0.0.7 and all problems solved. Apologies I thought I'd already done this
