### ISSUE TITLE
Error: Method GET must not have a request body

### ISSUE THREAD

**Issue by brunobraun** [olofd/react-native-signalr#41]
I can't use the function:

connection.start().done(() => {

as shown in the example.

This error occurs: Method GET must not have a request body.

"react": "16.0.0-beta.5"
"react-native": "0.49.3"
"react-native-signalr": "^1.0.5"

**Comment by Kebabpizza** [comment]
Same.

![image](https://user-images.githubusercontent.com/5185795/32172792-1cb64ce4-bd7d-11e7-9710-c99e53d3e944.png)

**Comment by olofd** [comment]
Fixing this tonight. Error mentioned here as well #32. New issue after yesterdays release. Use version 1.0.4 for now!

**Comment by olofd** [comment]
For reference. this changed introduced the issue I believe: https://github.com/olofd/react-native-signalr/commit/e3a8238b7f0da0b5d9d27826952896669bfde653

**Comment by olofd** [comment]
Should be fixed on npm 1.0.6
