### ISSUE TITLE
addQs method can't find this method from jquery '$.param'

### ISSUE THREAD

**Issue by cuixiaolu** [olofd/react-native-signalr#7]

**Comment by olofd** [comment]
Please give some more information regarding this. Preferably submit a PR.

**Comment by jonoirwinrsa** [comment]
This error occurs when trying to add headers as an object to the connection query string eg:
connection.qs = { 'Bearer' : token };
connection.start()...

If you use a serialised string it works

**Comment by olofd** [comment]
Sry for late response. Do you guys have any idea how to fix this? I can take a look this coming week, but I would want a bit more code that will reproduce the issue.

**Comment by jonoirwinrsa** [comment]
In my case I ended up not needing the query strings so I'm afraid I don't have a fix..

**Comment by olofd** [comment]
Ah. Ok. Then, if it's okay with you I'll close this for now. If more people report or have this issue we can open it again.

**Comment by thomasvm** [comment]
I've encountered the same scenario, needed the `.qs` for authentication to work on signalr hubs. Ended up adding the following code to my own project in order to polyfill `jQuery.param`

```
jQuery.param = (obj) => {
  const str = [];
  /* eslint-disable no-restricted-syntax,no-prototype-builtins */
  for (const p in obj) {
    if (obj.hasOwnProperty(p)) {
      str.push(
        `${encodeURIComponent(p)}=${encodeURIComponent(obj[p])}`
      );
    }
    /* eslint-enable no-restricted-syntax,no-prototype-builtins */
  }
  return str.join('&');
};
```
